<template>
  <div>
    <br />
    <!-- API call -->
    <div class="chatgptcall">
      <p>
        Explainability refers to the ability to describe the decisions of a machine learning model in a way that is understandable to the end users.
        <span class="AIgeneratedtext">{{ response }} </span>
      </p>
    </div>
    <br />

<div>
    <!-- Deployment Option -->
    <label><b>Stakeholder or Recipient of the explanation</b></label>
    <div class="info-container">
      <span class="info-icon">i</span>
      <div class="tooltip">API call for project-specific definition</div>
    </div>
     <!-- USelect Component -->
  <USelect
    placeholder="Select an option..."
    icon="i-heroicons-magnifying-glass-20-solid"
    v-model="stakeholder"
    style="width: 300px;"
    :options="stakeholder_list"
  />
    <br />

    <!-- Deployment Infrastructure -->
    <label><b>What aspects of the model/system need explanations?</b></label>
    <div class="info-container">
      <span class="info-icon">i</span>
      <div class="tooltip">API call for project-specific definition</div>
    </div>
    <UInput size="sm" v-model="aspects"/>
    <br />

    <!-- Inference Latency Metrics -->
    <label><b>In what situations or scenarios will the explanation be used?</b></label>
    <div class="info-container">
      <span class="info-icon">i</span>
      <div class="tooltip">API call for project-specific definition</div>
    </div>
    <UInput size="sm" v-model="scenarios"/>
    <br />

    <label><b>Who/what will be responsible for providing the explanation?</b></label>
    <div class="info-container">
      <span class="info-icon">i</span>
      <div class="tooltip">API call for project-specific definition</div>
    </div>
    <UInput size="sm" v-model="sourceofexplanation"/>
    <br />

    <label><b>What are the limitations to achieve that explanation?</b></label>
    <div class="info-container">
      <span class="info-icon">i</span>
      <div class="tooltip">API call for project-specific definition</div>
    </div>
    <UInput size="sm" v-model="limitations"/>
    <br />

    <!-- Dynamic Sentence -->
    <p class="input-group" style="padding-top: 10px; padding-bottom: 10px">
  <b>Scenario for Explainability:</b> [{{stakeholder}}] require explanation(s) from [{{sourceofexplanation}}] on [{{ aspects }}] when [{{ scenarios }}]. [{{ limitations}}] may make it challenging to provide the required explanations. 
</p>

<span class="AIgeneratedtext" id="cautiontext"> Highlighted text has been generated by AI </span>



  </div>


  </div>

<!-- -->

<p> </p>

</template>

<script lang="ts">
import { ref, onMounted, computed } from 'vue';
import { openai } from '~/composables/openai';

export default {
  name: 'InferenceLatencyForm',
  props: {
    MLTask: {
      required: true,
    },
    usageContext: {
      required: true,
    },
  },
  setup(props) {
    const response = ref('');
    const stakeholder = ref('');
    const stakeholder_list = ref('');
    const deploymentInfrastructure = ref<string | null>(null);
    const infrastructureDetails = ref<string | null>(null);
    const averageLatency = ref<string | null>(null);
    const mostLatency = ref<string | null>(null);
    const latencySeconds = ref<string | null>(null);

    //  first word of deploymentInfrastructure and detailsa
    const firstWordOfDeploymentInfrastructure = computed(() => {
      if (deploymentInfrastructure.value) {
        return deploymentInfrastructure.value.split(' ')[0]; 
      }
      return '';
    });

    const firstWordOfinfrastructureDetails = computed(() => {
      if (infrastructureDetails.value) {
        return infrastructureDetails.value.split(' ')[0]; 
      }
      return '';
    });

    const chat_role = 'You are a specialized data scientist with knowledge in both software engineering and data science.';

    const getChatResponse = async () => {
      const { chat } = openai();
      try {
        const messages = [
          {
            role: 'system',
            content: chat_role,
          },
          {
            role: 'user',
            content: `Write one sentence to explain the potential consequences of not considering explainability needs in the context of ${props.MLTask} and ${props.usageContext}. Use simple language that data scientists would understand. 
            write your recommendation as a list format using emojies like a caution emoji and a check off emoji for things that look good`,
          },
        ];

        const chatResponse = await chat(messages, 'gpt-3.5-turbo');
        const splitResponse = chatResponse.split('\n\n');
        response.value = splitResponse[0];
      } catch (error) {
        console.error('Error fetching chat response:', error);
      }
    };

    onMounted(() => {
      getChatResponse();
    });

    return {
      response,
      stakeholder,
      deploymentInfrastructure,
      infrastructureDetails,
      averageLatency,
      mostLatency,
      latencySeconds,
      firstWordOfDeploymentInfrastructure, 
      firstWordOfinfrastructureDetails,
    };
  },
};

// explainability list
const stakeholder_list = ['Wade Cooper', 'Arlene Mccoy', 'Devon Webb', 'Tom Cook', 'Tanya Fox', 'Hellen Schmidt', 'Caroline Schultz', 'Mason Heaney', 'Claudie Smitham', 'Emil Schaefer']

const stakeholder = ref(stakeholder_list[0])
</script>


<style scoped>
.AIgeneratedtext{
  background-color: #efe8c7;
}

.info-icon {
  display: inline-block;
  width: 20px;
  height: 20px;
  background-color: black;
  color: white;
  border-radius: 50%;
  text-align: center;
  line-height: 20px;
  font-weight: bold;
  font-family: Arial, cursive;
  font-size: 10px;
  cursor: pointer;
  margin-left: 5px;
  position: relative;
}

.tooltip {
  display: none;
  position: absolute;
  background-color: rgb(0, 0, 0);
  color: rgb(255, 255, 255);
  border: 1px solid #ccc;
  padding: 10px;
  font-size: 12px;
  border-radius: 5px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  width: 200px;
  top: 25px; 
  left: 0;
  z-index: 10;
}

.info-container:hover .tooltip {
  display: block;
}

.info-container {
  position: relative;
  display: inline-block;
}
</style>
