<template>
  <div class="quality-inspection">
    <div class="collapsable-header" @click="isExpanded = !isExpanded">
      <span class="collapsable-title">
        {{ isExpanded ? '▼' : '▶' }} Requirement Quality Inspection
      </span>
      <span class="collapsable-icons">
        <span class="warning">
          <Icon name="mdi:alert-circle-outline" class="icon-warning" />
          {{ Object.keys(critiques.warnings).length }}
        </span>
        <span class="error">
          <Icon name="mdi:close-circle-outline" class="icon-error" />
          {{ Object.keys(critiques.errors).length }}
        </span>
      </span>
    </div>

    <div v-if="isExpanded" class="collapsable-content">
      <p class="warning-title">Warnings (Qualities do not meet the standard):</p>
      <div v-for="(details, quality) in critiques.warnings" :key="quality" class="quality-item">
        <div class="quality-header" @click="toggleQuality(quality)">
          <span>{{ expandedQualities.includes(quality) ? '▼' : '▶' }} {{ quality }}</span>
        </div>
        <ul v-if="expandedQualities.includes(quality)" class="quality-details">
          <li v-for="(critique, index) in details" :key="index">{{ index + 1 }}. {{ critique }}</li>
        </ul>
      </div>

      <p class="error-title">Errors (Qualities are completely unsatisfactory):</p>
      <div v-for="(details, quality) in critiques.errors" :key="quality" class="quality-item">
        <div class="quality-header" @click="toggleQuality(quality)">
          <span>{{ expandedQualities.includes(quality) ? '▼' : '▶' }} {{ quality }}</span>
        </div>
        <ul v-if="expandedQualities.includes(quality)" class="quality-details">
          <li v-for="(critique, index) in details" :key="index">{{ index + 1 }}. {{ critique }}</li>
        </ul>
      </div>
    </div>

    <span class="AIgeneratedtext" id="cautiontext"> Highlighted text has been generated by AI </span>
  </div>
</template>


<script setup lang="ts">

interface Critique {
  warnings: Record<string, string[]>;
  errors: Record<string, string[]>;
}
const props = defineProps<{
  critiques: Critique;
}>();

const isExpanded = ref<boolean>(false);
const expandedQualities = ref<string[]>([]);

const toggleQuality = (quality: string) => {
  if (expandedQualities.value.includes(quality)) {
    expandedQualities.value = expandedQualities.value.filter(q => q !== quality);
  } else {
    expandedQualities.value.push(quality);
  }
};
</script>


<style>

.quality-inspection {
  border-radius: 8px;
  border: 1px solid #e2e8f0;
  overflow: hidden;
  background-color: white;
}

li {
  list-style-type: none;
  margin-bottom: 8px;
  padding: 0 12px;
}

li:last-child {
  margin-bottom: 0;
}

.collapsable-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  cursor: pointer;
  background-color: #f8fafc;
  transition: background-color 0.2s ease;
}

.collapsable-header:hover {
  background-color: #f1f5f9;
}

.collapsable-title {
  font-weight: 600;
  color: #334155;
  font-size: 0.95rem;
  display: flex;
  align-items: center;
  gap: 8px;
}

.collapsable-icons {
  display: flex;
  align-items: center;
  gap: 10px;
}

.warning, .error {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 3px 8px;
  border-radius: 12px;
  font-size: 0.75rem;
  font-weight: 600;
}

.warning {
  background-color: #fff8e1;
  color: #b45309;
}

.error {
  background-color: #fee9e9;
  color: #e53e3e;
}

.icon-warning {
  color: #f59e0b;
}

.icon-error {
  color: #ef4444;
}

.collapsable-content {
  padding: 16px;
  background-color: #f8fafc;
}

.warning-title, .error-title {
  font-weight: 600;
  color: #334155;
  font-size: 0.9rem;
  margin: 0 0 12px 0;
  padding-bottom: 8px;
  border-bottom: 1px solid #e2e8f0;
  display: flex;
  align-items: center;
  gap: 8px;
}

.warning-title {
  color: #b45309;
}

.error-title {
  color: #e53e3e;
}

.quality-item {
  margin-bottom: 12px;
}

.quality-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  background-color: #ffffff;
  border-radius: 6px;
  border: 1px solid #e2e8f0;
  cursor: pointer;
  transition: background-color 0.2s ease;
  font-size: 0.9rem;
  color: #334155;
  font-weight: 500;
}

.quality-header:hover {
  background-color: #f1f5f9;
}

.quality-details {
  margin-top: 8px;
  color: #555;
  background-color: #efe8c7;
  border-radius: 6px;
  padding: 10px;
  font-size: 0.9rem;
}

.quality-summary {
  margin-top: 12px;
  color: #555;
  font-size: 0.9rem;
  line-height: 1.5;
  background-color: #f9f9f9;
  border-radius: 4px;
  padding: 10px;
}

#cautiontext {
  display: block;
  text-align: center;
  font-size: 0.75rem;
  color: #78350f;
  font-style: italic;
  padding: 10px 12px;
  margin-top: 16px;
  background-color: #efe8c7;
  border-radius: 6px;
}

</style>