<template>
  <div class="quality-meter">
    <div class="quality-header">
      <h3 class="quality-title">{{ title }}</h3>
      <div class="percentage-badge" :class="percentageClass">{{ percentage }}%</div>
    </div>
    
    <div class="progress-container">
      <div class="progress-bar" :style="{ width: `${percentage}%`, backgroundColor: barColor }"></div>
    </div>
    
    <div class="quality-summary" v-if="summary && summary !== 'Summary'">
      <p>{{ summary }}</p>
    </div>

    <span class="AIgeneratedtext" id="cautiontext"> Highlighted text has been generated by AI </span>
    
    <div class="quality-critiques" v-if="critiques && critiques.length > 0">
      <div class="critiques-toggle" @click="showCritiques = !showCritiques">
        {{ showCritiques ? 'Hide Critiques' : 'View Critiques' }} 
        <i :class="showCritiques ? 'pi pi-chevron-up' : 'pi pi-chevron-down'"></i>
      </div>
      
      <div class="critiques-list" v-if="showCritiques">
        <div v-for="(critique, index) in critiques" :key="index" class="critique-item">
          <div class="set-label" v-if="critique.set">Requirement Set: {{ critique.set.join(', ') }}</div>
          <div v-for="(critic, cIndex) in critique.critics" :key="cIndex" class="critique-text">
            <i class="pi pi-exclamation-triangle"></i> {{ critic }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';

const props = defineProps({
  title: String,
  summary: String,
  percentage: Number,
  critiques: {
    type: Array,
    default: () => []
  }
});

const showCritiques = ref(false);

const barColor = computed(() => {
  if (props.percentage >= 90) return '#4CAF50'; // Green
  if (props.percentage >= 70) return '#8BC34A'; // Light Green
  if (props.percentage >= 50) return '#FFC107'; // Amber
  if (props.percentage >= 30) return '#FF9800'; // Orange
  return '#F44336'; // Red
});

const percentageClass = computed(() => {
  if (props.percentage >= 90) return 'status-green';
  if (props.percentage >= 70) return 'status-light-green';
  if (props.percentage >= 50) return 'status-amber';
  if (props.percentage >= 30) return 'status-orange';
  return 'status-red';
});
</script>

<style scoped>
.quality-meter {
  background-color: #fff;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  margin-bottom: 20px;
  padding: 16px;
  transition: all 0.3s ease;
}

.quality-meter:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.quality-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.quality-title {
  font-size: 1.1rem;
  font-weight: 600;
  margin: 0;
  color: #333;
}

.percentage-badge {
  padding: 4px 8px;
  border-radius: 16px;
  font-weight: 600;
  font-size: 14px;
  color: white;
}

.status-green { background-color: #4CAF50; }
.status-light-green { background-color: #8BC34A; }
.status-amber { background-color: #FFC107; color: #333; }
.status-orange { background-color: #FF9800; }
.status-red { background-color: #F44336; }

.progress-container {
  height: 8px;
  background-color: #f0f0f0;
  border-radius: 4px;
  overflow: hidden;
  margin-bottom: 12px;
}

.progress-bar {
  height: 100%;
  border-radius: 4px;
  transition: width 0.5s ease-in-out;
}

.quality-summary {
  margin-top: 12px;
  color: #555;
  font-size: 0.9rem;
  line-height: 1.5;
  background-color: #efe8c7;
  border-radius: 4px;
  padding: 10px;
}

.critiques-toggle {
  margin-top: 12px;
  color: #666;
  font-size: 0.85rem;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 6px;
  background-color: #f5f5f5;
  border-radius: 4px;
  transition: background-color 0.2s ease;
}

.critiques-toggle:hover {
  background-color: #ececec;
}

.critiques-toggle i {
  margin-left: 4px;
}

.critiques-list {
  margin-top: 12px;
  border-top: 1px solid #eee;
  padding-top: 12px;
}

.critique-item {
  margin-bottom: 10px;
  padding: 8px;
  background-color: #fff9e6;
  border-left: 3px solid #FFC107;
  border-radius: 0 4px 4px 0;
}

.set-label {
  font-weight: 600;
  font-size: 0.8rem;
  margin-bottom: 6px;
  color: #444;
}

.critique-text {
  font-size: 0.85rem;
  color: #555;
  margin-bottom: 6px;
  padding-left: 8px;
  display: flex;
  align-items: flex-start;
}

.critique-text i {
  color: #FF9800;
  margin-right: 6px;
  margin-top: 3px;
}
</style>